# Place any default configuration for solr_wrapper here
# port: 8983
collection:
  dir: solr/config
#  name: spotlight_day_demo
  
instance_dir: 'solr/instance/solr'
download_dir: 'solr/instance'
port: '8991'
persist: true

